version: '3.7'

services:
  api:
    container_name: etcetera_api
    build:
      context: ./services/api
      dockerfile: ./docker/Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: etcetera_db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=etcetera
      - POSTGRES_PASSWORD=etc689
      - POSTGRES_DB=etcetera_dev

volumes:
  postgres_data: