version: '3.7'

services:
  api:
    build:
      context: ./services/api
      dockerfile: ./services/api/docker/Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume: