version: "3.7"
services:

  app:
    container_name: flask_api
    build:
      context: .
      dockerfile: ./src/docker/Dockerfile
    env_file: ./.env
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - ./src:/opt/src

  database:
    container_name: postgres
    env_file: ./.env
    image: postgres:latest
    ports:
      - 5432:5432

volumes:
    db_volume:
